create table public.m365_partner_settings (
  id boolean primary key default true,
  constraint m365_partner_settings_singleton check (id),
  partner_tenant_id text,
  client_id text,
  client_secret text,
  cached_refresh_token text,
  obo_user_hint text, -- the connected account's UPN, shown in settings — not a secret
  connected_at timestamptz,
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles (id) on delete set null
);

create trigger m365_partner_settings_set_updated_at before update on public.m365_partner_settings
  for each row execute procedure public.set_updated_at();

alter table public.m365_partner_settings enable row level security;
-- No policy for `authenticated` — service-role only, same posture as
-- autotask_settings/ninjaone_settings.

alter table public.clients add column if not exists m365_tenant_id text;

create table public.m365_license_summary (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.clients (id) on delete cascade,
  sku_part_number text not null,
  consumed_units integer not null,
  enabled_units integer not null,
  suspended_units integer not null default 0,
  capability_status text,
  last_synced_at timestamptz not null default now(),
  unique (client_id, sku_part_number)
);

create index m365_license_summary_client_idx on public.m365_license_summary (client_id);

alter table public.m365_license_summary enable row level security;
create policy "m365_license_summary full access for authenticated" on public.m365_license_summary
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
