-- One row per client — latest snapshot, not history.
create table public.m365_secure_score (
  client_id uuid primary key references public.clients (id) on delete cascade,
  current_score numeric not null,
  max_score numeric not null,
  licensed_user_count integer,
  score_created_date_time timestamptz,
  last_synced_at timestamptz not null default now()
);

-- Only genuine gaps (current_score < max_score) are stored, biggest
-- deficit first — a fully-implemented control isn't actionable, so it's
-- left out rather than padding the list.
create table public.m365_secure_score_gaps (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.clients (id) on delete cascade,
  control_name text not null,
  title text,
  category text,
  current_score numeric not null,
  max_score numeric,
  remediation text,
  action_url text,
  tier text,
  implementation_cost text,
  last_synced_at timestamptz not null default now(),
  unique (client_id, control_name)
);

create index m365_secure_score_gaps_client_idx on public.m365_secure_score_gaps (client_id);

alter table public.m365_secure_score enable row level security;
create policy "m365_secure_score full access for authenticated" on public.m365_secure_score
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

alter table public.m365_secure_score_gaps enable row level security;
create policy "m365_secure_score_gaps full access for authenticated" on public.m365_secure_score_gaps
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
