-- ============================================================================
-- Three additions, from comparing the Proposals feature against an actual
-- Autotask-generated quote (Marathon Hardware, quote #849):
--
-- 1. proposal_number — a short, human-friendly reference ("Proposal #142")
--    for phone/email conversations, the same role Autotask's own
--    "Quote Number" plays. `generated by default as identity` (same
--    pattern as 019/020) rather than a plain integer default, so existing
--    rows backfill in insertion order and every future insert gets the
--    next value with no application-side counter to get out of sync. The
--    access_token in the URL remains the only real credential — this
--    number is never accepted as a lookup key anywhere, purely a label.
--
-- 2. proposal_line_items.list_price — the pre-discount reference price,
--    alongside the existing unit_price (the actual charged price, used for
--    every total). Mirrors the quote template's "Unit Price" vs "Adjusted
--    Unit Price" columns. Null means "nothing to compare against" — most
--    lines, including every hand-typed one, have no list price and just
--    show their one price as before.
--
-- 3. proposals.accepted_signature_path — where a prospect's drawn
--    signature image lives (private storage), captured alongside the
--    typed name and authority checkbox at acceptance. Null for a
--    staff-recorded (accepted_via='staff') acceptance, which has no
--    signature pad to draw on.
--
-- Run this in the Supabase SQL Editor AFTER 131.
-- ============================================================================

alter table public.proposals
  add column if not exists proposal_number bigint generated by default as identity,
  add column if not exists accepted_signature_path text;

-- Not `unique not null` from the start: a bare `add column ... generated by
-- default as identity` already guarantees uniqueness and backfills every
-- existing row, but Postgres computing that backfill and then enforcing a
-- separate unique index in the same statement is unnecessarily fragile on a
-- live table. The identity property alone is enough — this index is just
-- for fast lookups if the number is ever searched on.
create unique index if not exists proposals_proposal_number_idx
  on public.proposals (proposal_number);

alter table public.proposal_line_items
  add column if not exists list_price numeric(12,2);

insert into storage.buckets (id, name, public)
values ('proposal-signatures', 'proposal-signatures', false)
on conflict (id) do nothing;

-- Staff-only, same posture as every other proposal bucket. The public
-- accept action writes the signature image via the service-role admin
-- client, which bypasses these policies entirely — they exist for staff
-- viewing a captured signature from the editor, not for the public route.
create policy "proposal-signatures bucket readable by staff" on storage.objects
  for select using (bucket_id = 'proposal-signatures' and public.is_staff());
create policy "proposal-signatures bucket insertable by staff" on storage.objects
  for insert with check (bucket_id = 'proposal-signatures' and public.is_staff());
create policy "proposal-signatures bucket deletable by staff" on storage.objects
  for delete using (bucket_id = 'proposal-signatures' and public.is_staff());
