-- ============================================================================
-- Three new per-client Microsoft 365 sections: Conditional Access policies,
-- Intune devices, and Intune policies (device configuration + compliance).
-- Same shape as the existing m365_license_summary/m365_secure_score* tables
-- from 019/020 — a delete-then-reinsert snapshot per client, refreshed by
-- the same three mechanisms already in place (the m365-partner-sync cron,
-- the manual "Sync M365" button, and the throttled auto-sync-on-visit).
--
-- RLS uses public.is_staff() rather than the older
-- `auth.role() = 'authenticated'` posture 019/020/021 used — is_staff()
-- (introduced in 064) is this app's current convention, and there's no
-- reason for a brand-new table to resurrect the coarser, earlier one.
--
-- Every new column here requires a Graph permission that is NOT yet
-- consented on any client's Azure app registration (Policy.Read.All,
-- DeviceManagementManagedDevices.Read.All, DeviceManagementConfiguration.Read.All)
-- — same "isolated per client, degrades to an empty/placeholder tab until
-- an admin re-consents" posture as the already-dormant AuditLog.Read.All
-- calls in m365-partner.ts. Nothing here requires every existing linked
-- client to do anything; a client whose admin hasn't re-consented just
-- keeps seeing "not yet available" on these three new tabs.
--
-- Run this in the Supabase SQL Editor AFTER 133.
-- ============================================================================

create table public.m365_conditional_access_policies (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.clients (id) on delete cascade,
  -- The tenant's own Graph object id — informational, not this row's key,
  -- since a client's own delete-then-reinsert already scopes uniqueness.
  policy_id text not null,
  display_name text not null,
  -- One of Microsoft's own three values: 'enabled', 'disabled',
  -- 'enabledForReportingButNotEnforced' (report-only mode).
  state text not null,
  created_date_time timestamptz,
  modified_date_time timestamptz,
  last_synced_at timestamptz not null default now(),
  unique (client_id, policy_id)
);

create index m365_conditional_access_policies_client_idx
  on public.m365_conditional_access_policies (client_id);

alter table public.m365_conditional_access_policies enable row level security;
create policy "m365_conditional_access_policies full access for staff" on public.m365_conditional_access_policies
  for all using (public.is_staff()) with check (public.is_staff());

create table public.m365_intune_devices (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.clients (id) on delete cascade,
  device_id text not null,
  device_name text not null,
  operating_system text,
  os_version text,
  compliance_state text,
  managed_device_owner_type text,
  user_principal_name text,
  model text,
  manufacturer text,
  serial_number text,
  is_encrypted boolean,
  last_sync_date_time timestamptz,
  last_synced_at timestamptz not null default now(),
  unique (client_id, device_id)
);

create index m365_intune_devices_client_idx on public.m365_intune_devices (client_id);

alter table public.m365_intune_devices enable row level security;
create policy "m365_intune_devices full access for staff" on public.m365_intune_devices
  for all using (public.is_staff()) with check (public.is_staff());

-- Device configuration (v1.0, stable) and device compliance (beta only —
-- Microsoft has no v1.0 equivalent for listing these) policies share one
-- table, distinguished by policy_kind. The unique constraint includes
-- policy_kind, not just policy_id: the two are different Graph resource
-- types with independently-issued ids, and nothing guarantees they never
-- collide.
create table public.m365_intune_policies (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.clients (id) on delete cascade,
  policy_id text not null,
  policy_kind text not null check (policy_kind in ('configuration', 'compliance')),
  display_name text not null,
  version integer,
  created_date_time timestamptz,
  modified_date_time timestamptz,
  last_synced_at timestamptz not null default now(),
  unique (client_id, policy_kind, policy_id)
);

create index m365_intune_policies_client_idx on public.m365_intune_policies (client_id);

alter table public.m365_intune_policies enable row level security;
create policy "m365_intune_policies full access for staff" on public.m365_intune_policies
  for all using (public.is_staff()) with check (public.is_staff());
