-- ============================================================================
-- Four more per-client Microsoft 365 sections, same delete-then-reinsert
-- snapshot shape as 019/020/134: Identity Protection (risky users + risk
-- detections), MFA/sign-in audit, and mailbox usage.
--
-- Two of these reuse fetchers that already existed in m365-partner.ts
-- before this migration (fetchUserRegistrationDetails,
-- fetchUserSignInActivity, fetchMailboxUsageDetail) but were only ever
-- wired into the account-wide rollup pages (m365-lookups.ts/m365-itdr.ts),
-- never synced into a per-client table. Identity Protection (risky users /
-- risk detections) is genuinely new — no code existed for it before this.
--
-- None of the four permissions behind these (IdentityRiskyUser.Read.All,
-- IdentityRiskEvent.Read.All, AuditLog.Read.All, Reports.Read.All) are
-- consented on any client's Azure app registration yet — same "isolated
-- per client, degrades to empty until re-consented" posture as 134.
-- Risk detections additionally requires an Entra ID P1/P2 license on the
-- tenant (Microsoft's own requirement, not something this app can work
-- around) — a client without that license gets a clean empty list, not
-- an error.
--
-- Run this in the Supabase SQL Editor AFTER 134.
-- ============================================================================

create table public.m365_risky_users (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.clients (id) on delete cascade,
  -- Graph's riskyUser.id — this IS the user's own object id, not a
  -- separate risk-record id (confirmed on Microsoft's own resource docs).
  user_id text not null,
  user_principal_name text,
  display_name text,
  risk_level text,
  risk_state text,
  risk_detail text,
  risk_last_updated_date_time timestamptz,
  last_synced_at timestamptz not null default now(),
  unique (client_id, user_id)
);

create index m365_risky_users_client_idx on public.m365_risky_users (client_id);

alter table public.m365_risky_users enable row level security;
create policy "m365_risky_users full access for staff" on public.m365_risky_users
  for all using (public.is_staff()) with check (public.is_staff());

create table public.m365_risk_detections (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.clients (id) on delete cascade,
  detection_id text not null,
  user_principal_name text,
  display_name text,
  risk_event_type text,
  risk_level text,
  risk_state text,
  risk_detail text,
  ip_address text,
  detected_date_time timestamptz,
  last_synced_at timestamptz not null default now(),
  unique (client_id, detection_id)
);

create index m365_risk_detections_client_idx on public.m365_risk_detections (client_id);

alter table public.m365_risk_detections enable row level security;
create policy "m365_risk_detections full access for staff" on public.m365_risk_detections
  for all using (public.is_staff()) with check (public.is_staff());

-- MFA registration (AuditLog.Read.All, /reports/authenticationMethods/
-- userRegistrationDetails) and sign-in activity (same permission,
-- signInActivity on /users) joined per user into one row — the same join
-- m365-itdr.ts already does for the account-wide rollup, but with real
-- columns here instead of a flattened issues[] list, since a per-client
-- table benefits from being filterable/sortable on each signal
-- independently.
create table public.m365_user_audit (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.clients (id) on delete cascade,
  user_principal_name text not null,
  display_name text,
  is_admin boolean not null default false,
  is_mfa_registered boolean not null default false,
  is_mfa_capable boolean not null default false,
  user_type text,
  account_enabled boolean not null default true,
  last_successful_sign_in timestamptz,
  last_synced_at timestamptz not null default now(),
  unique (client_id, user_principal_name)
);

create index m365_user_audit_client_idx on public.m365_user_audit (client_id);

alter table public.m365_user_audit enable row level security;
create policy "m365_user_audit full access for staff" on public.m365_user_audit
  for all using (public.is_staff()) with check (public.is_staff());

create table public.m365_mailbox_usage (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.clients (id) on delete cascade,
  user_principal_name text not null,
  display_name text,
  storage_used_bytes bigint not null default 0,
  prohibit_send_receive_quota_bytes bigint not null default 0,
  last_synced_at timestamptz not null default now(),
  unique (client_id, user_principal_name)
);

create index m365_mailbox_usage_client_idx on public.m365_mailbox_usage (client_id);

alter table public.m365_mailbox_usage enable row level security;
create policy "m365_mailbox_usage full access for staff" on public.m365_mailbox_usage
  for all using (public.is_staff()) with check (public.is_staff());
