import { NextRequest, NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/server";
import { requirePermission } from "@/lib/permissions";
import { QUARTERLY_REVIEW_PDF_BUCKET } from "@/lib/quarterly-review-data";

export const dynamic = "force-dynamic";

/**
 * Redirects to a short-lived signed URL for one of a review's standalone
 * extra-section PDFs (Device Health, 365 Licenses, ...) — staff-only,
 * unlike /api/quarterly-review-pdf/[id] (which a client can also reach
 * once a review is sent): these are internal review tooling, generated by
 * generateQuarterlyReviewSectionPdf and never emailed with a client-facing
 * link of their own (they go out as plain email attachments instead).
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string; sectionKey: string }> }
) {
  if (!(await requirePermission("manage_quarterly_reviews"))) {
    return NextResponse.json({ error: "Not authorized." }, { status: 403 });
  }

  const { id, sectionKey } = await params;
  const admin = createAdminClient();
  const { data: row } = await admin
    .from("quarterly_review_section_pdfs")
    .select("storage_path")
    .eq("review_id", id)
    .eq("section_key", sectionKey)
    .maybeSingle();
  if (!row) {
    return NextResponse.json({ error: "No PDF generated for this section yet." }, { status: 404 });
  }

  const { data, error } = await admin.storage.from(QUARTERLY_REVIEW_PDF_BUCKET).createSignedUrl(row.storage_path, 60);
  if (error || !data) {
    return NextResponse.json({ error: error?.message ?? "Could not sign URL." }, { status: 500 });
  }

  return NextResponse.redirect(data.signedUrl);
}
